/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sisagencia.view;

import br.com.sisagencia.controller.EmpresaController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Jhonatan Nobre
 */
public class DescktopGerenciaEmpresasView extends javax.swing.JInternalFrame {
private EmpresaController empr;
    /**
     * Creates new form NewJFrame
     */
    public DescktopGerenciaEmpresasView() throws Exception {
        empr = new EmpresaController();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabelcnpj = new javax.swing.JLabel();
        jLabelRazaoSocial = new javax.swing.JLabel();
        jLabelRamoAtiv = new javax.swing.JLabel();
        jTextFieldcnpj = new javax.swing.JTextField();
        jTextFieldrazaoSocial = new javax.swing.JTextField();
        jTextFieldsituacaoEmpresa = new javax.swing.JTextField();
        jTextFieldRamoAtiv = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonexcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSituacaoEmpresa = new javax.swing.JLabel();
        jLabeldescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabelFundo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelcnpj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelcnpj.setText("cnpj");
        getContentPane().add(jLabelcnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 50, -1));

        jLabelRazaoSocial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRazaoSocial.setText("Razão Social");
        getContentPane().add(jLabelRazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 90, -1));

        jLabelRamoAtiv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRamoAtiv.setText("Ramo Atividade:");
        getContentPane().add(jLabelRamoAtiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 110, -1));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empr.empresa.cnpj}"), jTextFieldcnpj, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldcnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcnpjActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldcnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 190, 30));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empr.empresa.razaoSocial}"), jTextFieldrazaoSocial, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldrazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldrazaoSocialActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldrazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 200, 30));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empr.empresa.statusSituacao}"), jTextFieldsituacaoEmpresa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldsituacaoEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsituacaoEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldsituacaoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 330, 30));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empr.empresa.ramoAtividade}"), jTextFieldRamoAtiv, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jTextFieldRamoAtiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 330, 30));

        jButtonCadastrar.setText("CADASTRAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 110, 30));

        jButtonexcluir.setText("EXCLUIR");
        jButtonexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 110, 30));

        jButtonCancelar.setText("FECHAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 110, 30));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTitulo.setText("CADASTRO DE EMPRESAS");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabelSituacaoEmpresa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSituacaoEmpresa.setText("Situação da Empresa:");
        getContentPane().add(jLabelSituacaoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, -1));

        jLabeldescricao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabeldescricao.setText("Descrição dos Serviços Prestados:");
        getContentPane().add(jLabeldescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 220, -1));

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empr.empresa.descrServico}"), jTextAreaDescricao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(jTextAreaDescricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 330, -1));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${empr.empresas}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTable2);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idempresa}"));
        columnBinding.setColumnName("Idempresa");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cnpj}"));
        columnBinding.setColumnName("Cnpj");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${razaoSocial}"));
        columnBinding.setColumnName("Razao Social");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${statusSituacao}"));
        columnBinding.setColumnName("Status Situacao");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ramoAtividade}"));
        columnBinding.setColumnName("Ramo Atividade");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descrServico}"));
        columnBinding.setColumnName("Descr Servico");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 410, 590, 170));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisagencia/imagens/fundoCadastro2.png"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -300, 590, 1060));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldcnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcnpjActionPerformed

    private void jTextFieldrazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldrazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldrazaoSocialActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        try {
            empr.inserirEmpresa();
            JOptionPane.showMessageDialog(null, "Empresa Cadastrada com Sucesso!", "Aviso!", JOptionPane.PLAIN_MESSAGE);
            jTextFieldcnpj.setText(null);
            jTextFieldrazaoSocial.setText(null);
            jTextFieldsituacaoEmpresa.setText(null);
            jTextFieldRamoAtiv.setText(null);
            jTextAreaDescricao.setText(null);
            
            jButtonCadastrar.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
            jTextFieldcnpj.setEnabled(true);
            jTextFieldrazaoSocial.setEnabled(true);
            jTextFieldsituacaoEmpresa.setEnabled(true);
            jTextFieldRamoAtiv.setEnabled(true);
            jTextAreaDescricao.setEnabled(true);            
            
    }
});
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Cadastrar Empresa!", "Alerta!", JOptionPane.ERROR_MESSAGE);
        Logger.getLogger(DescktopGerenciaEmpresasView.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldsituacaoEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsituacaoEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsituacaoEmpresaActionPerformed

    private void jButtonexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexcluirActionPerformed
        //NÃO DEIXA EXCLUIR SE NÃO ESTIVER SELECIONADO ALGUMA LINHA
        if (jTable2.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha da tabela para excluir !");
            return;
        }

        int result = JOptionPane.showConfirmDialog(this, "você tem certeza?", "Remover a Empresa Atual", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == 0) {
            try {
               int selecionado = jTable2.getSelectedRow();
               empr.removerEmpresa((int) jTable2.getValueAt(selecionado,0));
               JOptionPane.showMessageDialog(this, "Empresa Removida com sucesso !");
            
            } catch (NoSuchAlgorithmException ex) {
               Logger.getLogger(DescktopGerenciarUsuariosView.class.getName()).log(Level.SEVERE, null, ex);
           } catch (Exception ex) {
               Logger.getLogger(DescktopGerenciarUsuariosView.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_jButtonexcluirActionPerformed

    public EmpresaController getEmpr() {
        return empr ;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonexcluir;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelRamoAtiv;
    private javax.swing.JLabel jLabelRazaoSocial;
    private javax.swing.JLabel jLabelSituacaoEmpresa;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelcnpj;
    private javax.swing.JLabel jLabeldescricao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldRamoAtiv;
    private javax.swing.JTextField jTextFieldcnpj;
    private javax.swing.JTextField jTextFieldrazaoSocial;
    private javax.swing.JTextField jTextFieldsituacaoEmpresa;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
