/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sisagencia.view;

import br.com.sisagencia.controller.UsuarioController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhonatan Nobre
 */
public class DescktopGerenciarUsuariosView extends javax.swing.JInternalFrame {
private UsuarioController uc;
    /**
     * Creates new form NewJFrame
     */
    public DescktopGerenciarUsuariosView() {
        uc = new UsuarioController();
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabelLogin = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldlogin = new javax.swing.JTextField();
        jPasswordFieldsenha = new javax.swing.JPasswordField();
        jButtonApagar = new javax.swing.JButton();
        jButtonCANCELAR = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableuser = new javax.swing.JTable();
        jLabelFundo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLogin.setText("Login:");
        getContentPane().add(jLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 50, -1));

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 50, -1));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${uc.usuario.login}"), jTextFieldlogin, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldloginActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 190, 30));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${uc.usuario.senha}"), jPasswordFieldsenha, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        getContentPane().add(jPasswordFieldsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 190, 30));

        jButtonApagar.setText("APAGAR");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 110, 30));

        jButtonCANCELAR.setText("SAIR");
        jButtonCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCANCELARActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCANCELAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 110, 30));

        jButtonCadastrar.setText("CADASTRAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 110, 30));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTitulo.setText("GERENCIAMENTO DE USUÁRIOS");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${uc.usuarios}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jTableuser);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${login}"));
        columnBinding.setColumnName("Login");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTableuser);
        if (jTableuser.getColumnModel().getColumnCount() > 0) {
            jTableuser.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 590, 180));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisagencia/imagens/fundoCadastro2.png"))); // NOI18N
        jLabelFundo.setText("jLabel2");
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 390));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldloginActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        try {
            uc.salvar();
            JOptionPane.showMessageDialog(null, "Usuário Cadastrado com Sucesso!", "Atenção!", JOptionPane.PLAIN_MESSAGE);
         jTextFieldlogin.setText(null);
        jPasswordFieldsenha.setText(null);
        
        jButtonCadastrar.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
            jTextFieldlogin.setEnabled(true);
            jPasswordFieldsenha.setEnabled(true);
        }
            
    });
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(CadastroUsuarioView.class.getName()).log(Level.SEVERE, null, ex);
  JOptionPane.showMessageDialog(null, "Erro ao Cadastrar Usuário!", "Alerta!", JOptionPane.ERROR_MESSAGE);
       
        }
        
        jTextFieldlogin.requestFocus();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
         //NÃO DEIXA EXCLUIR SE NÃO ESTIVER SELECIONADO ALGUMA LINHA
       if(jTableuser.getSelectedRow() == -1) {
           JOptionPane.showMessageDialog(this,"Selecione uma linha da tabela para excluir !");
           return;
       }

       int result = JOptionPane.showConfirmDialog(this,"você tem certeza?" , "Remover o Usuário Atual" ,JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE );
       if(result == 0) {
           try {
               
               int selecionado = jTableuser.getSelectedRow();
               uc.removerUsuario((int) jTableuser.getValueAt(selecionado,0));
               JOptionPane.showMessageDialog(this, "Usuario Removida com sucesso !");
               
           } catch (NoSuchAlgorithmException ex) {
               Logger.getLogger(DescktopGerenciarUsuariosView.class.getName()).log(Level.SEVERE, null, ex);
           } catch (Exception ex) {
               Logger.getLogger(DescktopGerenciarUsuariosView.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       
       
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCANCELARActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCANCELARActionPerformed

    public UsuarioController getUc() {
        return uc;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonCANCELAR;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPasswordField jPasswordFieldsenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableuser;
    private javax.swing.JTextField jTextFieldlogin;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
